apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-configmap
data: 
  index.html: |
      "{{ .Values.nginxtext }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecp-conf
data: 
  setRule.sh: |
    #!/bin/bash
    curl -i --location --request PUT 'http://{{ .Values.ecpendpoint }}/EcpFront/applications/clovim/traffic_rules/demo' \
    --header 'Content-Type: application/json' \
    --header 'Cookie: JSESSIONID=node08xm6chuudrv5zjaq41gm4jqy43512.node0' \
    --data-raw '{
        "trafficRuleId": "demo",
        "trafficFilter": [
            {
                "dstAddress": [
                    "{{ .Values.publicIP }}"
                ]
            }
        ],
        "dstInterface": {
            "dstIpAddress":  "'"$PODIP"'"
        }
    }'
      
      

